name: pre-commit
on:
  pull_request:
  push:
    branches: [main, '*.x']
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
    - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
      with:
        python-version: 3.x
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
    - uses: pre-commit-ci/lite-action@1384014f1a0d9c9e0656844e4e6e0f3554b1b3e7 # v1.0.3
      if: ${{ !cancelled() }}
